name: la-realite

type: 'nodejs:16'

disk: 512

hooks:
  build: |
    npm run build:larealite

web:
  locations:
    /:
      # The public directory relative to the app root.
      root: 'examples/js/media/dist'

      # What files to use when serving a directory.
      index:
        - index.html
